# mineperc.restoreprivacy.online — Perccent PERC pool.
server {
    listen 80;
    listen [::]:80;
    server_name mineperc.restoreprivacy.online;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        default_type text/plain;
    }

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://127.0.0.1:8011/;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name mineperc.restoreprivacy.online;
    ssl_certificate /etc/letsencrypt/live/evolve.restoreprivacy.online-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/evolve.restoreprivacy.online-0001/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://127.0.0.1:8011/;
    }
}
